-- AlterTable
ALTER TABLE "orders" ADD COLUMN     "laborValue" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "materialValue" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "totalValue" DOUBLE PRECISION DEFAULT 0;
