# services/redis.yml
services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    command: redis-server --appendonly yes --requirepass 123456
    volumes:
      - D:/builds/docker/redis:/data
    networks:
      - internal
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "123456", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5