# docker-compose.yml


include:
  - services/postgres.yml
  - services/postgres-evo.yml
  - services/redis.yml
  - services/evolution.yml
  

volumes:
  postgres_data:
  postgres_evo_data:
  redis_data:
  evolution_instances:

networks:
  internal:
    name: ${CLIENT_SLUG}-network
    driver: bridge